In [1]:
import pandas as pd
d=pd.read_csv("C:\\Users\\depak\\OneDrive\\Desktop\\rkkk\\bbb.csv")
df=pd.DataFrame(d)
print(d)

                    tournament           home  home_goal  away_goal  \
0               Premier League        Arsenal        0.0        0.0
1               Premier League      Leicester        0.0        0.0
2               Premier League      Liverpool        0.0        0.0
3               Premier League    Bournemouth        0.0        0.0
4               Premier League         Fulham        0.0        0.0
...                        ...            ...        ...        ...
21796  England National League  Kidderminster        2.0        2.0
21797  England National League   Lincoln City        1.0        1.0
21798  England National League        Torquay        1.0        0.0
21799  England National League       Tranmere        1.0        0.0
21800  England National League        Welling        1.0        0.0

               away  home_corner  away_corner  home_attack  away_attack  \
0           Chelsea          0.0          0.0          NaN          NaN
1           Everton          0.0          0.0          NaN          NaN
2         Tottenham          0.0          0.0          NaN          NaN
3             Leeds          0.0          0.0          NaN          NaN
4          Man City          0.0          0.0          NaN          NaN
...             ...          ...          ...          ...          ...
21796       Grimsby          2.0          4.0          NaN          NaN
21797    Cheltenham          8.0          6.0          NaN          NaN
21798  Macclesfield          4.0          7.0          NaN          NaN
21799        Woking          2.0          7.0          NaN          NaN
21800      Guiseley          2.0          3.0          NaN          NaN

       home_shots  away_shots      time        date  ht_diff  at_diff  \
0             NaN         NaN  20:00:00  2023-05-02      0.0      0.0
1             NaN         NaN  20:00:00  2023-05-01      0.0      0.0
2             NaN         NaN  16:30:00  2023-04-30      0.0      0.0
3             NaN         NaN  14:00:00  2023-04-30      0.0      0.0
4             NaN         NaN  14:00:00  2023-04-30      0.0      0.0
...           ...         ...       ...         ...      ...      ...
21796         NaN         NaN  15:00:00  2015-08-08      0.0      0.0
21797         NaN         NaN  15:00:00  2015-08-08      0.0      0.0
21798         NaN         NaN  15:00:00  2015-08-08      1.0     -1.0
21799         NaN         NaN  15:00:00  2015-08-08      1.0     -1.0
21800         NaN         NaN  15:00:00  2015-08-08      1.0     -1.0

      ht_result at_result  total_corners
0          DRAW      DRAW            0.0
1          DRAW      DRAW            0.0
2          DRAW      DRAW            0.0
3          DRAW      DRAW            0.0
4          DRAW      DRAW            0.0
...         ...       ...            ...
21796      DRAW      DRAW            6.0
21797      DRAW      DRAW           14.0
21798       WON      LOST           11.0
21799       WON      LOST            9.0
21800       WON      LOST            5.0

[21801 rows x 18 columns]

In [2]:
df.head()

,tournament,home,home_goal,away_goal,away,home_corner,away_corner,home_attack,away_attack,home_shots,away_shots,time,date,ht_diff,at_diff,ht_result,at_result,total_corners
0,Premier League,Arsenal,0.0,0.0,Chelsea,0.0,0.0,NaN,NaN,NaN,NaN,20:00:00,2023-05-02,0.0,0.0,DRAW,DRAW,0.0
1,Premier League,Leicester,0.0,0.0,Everton,0.0,0.0,NaN,NaN,NaN,NaN,20:00:00,2023-05-01,0.0,0.0,DRAW,DRAW,0.0
2,Premier League,Liverpool,0.0,0.0,Tottenham,0.0,0.0,NaN,NaN,NaN,NaN,16:30:00,2023-04-30,0.0,0.0,DRAW,DRAW,0.0
3,Premier League,Bournemouth,0.0,0.0,Leeds,0.0,0.0,NaN,NaN,NaN,NaN,14:00:00,2023-04-30,0.0,0.0,DRAW,DRAW,0.0
4,Premier League,Fulham,0.0,0.0,Man City,0.0,0.0,NaN,NaN,NaN,NaN,14:00:00,2023-04-30,0.0,0.0,DRAW,DRAW,0.0

In [3]:
df.tail()

,tournament,home,home_goal,away_goal,away,home_corner,away_corner,home_attack,away_attack,home_shots,away_shots,time,date,ht_diff,at_diff,ht_result,at_result,total_corners
21796,England National League,Kidderminster,2.0,2.0,Grimsby,2.0,4.0,NaN,NaN,NaN,NaN,15:00:00,2015-08-08,0.0,0.0,DRAW,DRAW,6.0
21797,England National League,Lincoln City,1.0,1.0,Cheltenham,8.0,6.0,NaN,NaN,NaN,NaN,15:00:00,2015-08-08,0.0,0.0,DRAW,DRAW,14.0
21798,England National League,Torquay,1.0,0.0,Macclesfield,4.0,7.0,NaN,NaN,NaN,NaN,15:00:00,2015-08-08,1.0,-1.0,WON,LOST,11.0
21799,England National League,Tranmere,1.0,0.0,Woking,2.0,7.0,NaN,NaN,NaN,NaN,15:00:00,2015-08-08,1.0,-1.0,WON,LOST,9.0
21800,England National League,Welling,1.0,0.0,Guiseley,2.0,3.0,NaN,NaN,NaN,NaN,15:00:00,2015-08-08,1.0,-1.0,WON,LOST,5.0

In [4]:
df.sort_values("total_corners")

,tournament,home,home_goal,away_goal,away,home_corner,away_corner,home_attack,away_attack,home_shots,away_shots,time,date,ht_diff,at_diff,ht_result,at_result,total_corners
0,Premier League,Arsenal,0.0,0.0,Chelsea,0.0,0.0,NaN,NaN,NaN,NaN,20:00:00,2023-05-02,0.0,0.0,DRAW,DRAW,0.0
8301,England League 1,Accrington Stanley,0.0,0.0,Cambridge Utd,0.0,0.0,NaN,NaN,NaN,NaN,15:00:00,2023-04-29,0.0,0.0,DRAW,DRAW,0.0
17420,England League 2,Bury,0.0,0.0,Southend,0.0,0.0,NaN,NaN,NaN,NaN,15:00:00,2015-03-28,0.0,0.0,DRAW,DRAW,0.0
17770,England League 2,Shrewsbury,0.0,0.0,Carlisle,0.0,0.0,NaN,NaN,NaN,NaN,19:45:00,2014-09-16,0.0,0.0,DRAW,DRAW,0.0
17857,England National League,Aldershot,0.0,0.0,Altrincham,0.0,0.0,NaN,NaN,NaN,NaN,17:30:00,2023-04-29,0.0,0.0,DRAW,DRAW,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2888,Premier League,Norwich,1.0,2.0,Leicester,17.0,8.0,NaN,NaN,NaN,NaN,15:00:00,2015-10-03,-1.0,1.0,LOST,WON,25.0
17143,England League 2,Barnet,2.0,0.0,Exeter,10.0,15.0,NaN,NaN,NaN,NaN,15:01:22,2015-10-31,2.0,-2.0,WON,LOST,25.0
7801,England Championship,Bolton,1.0,1.0,Blackpool,17.0,9.0,NaN,NaN,NaN,NaN,15:00:00,2015-04-04,0.0,0.0,DRAW,DRAW,26.0
12040,England League 1,Bury,1.0,0.0,Doncaster,9.0,18.0,NaN,NaN,NaN,NaN,15:00:00,2016-04-09,1.0,-1.0,WON,LOST,27.0
20836,England National League,Guiseley,3.0,2.0,Torquay,16.0,11.0,37.0,34.0,20.0,18.0,15:00:26,2017-08-19,1.0,-1.0,WON,LOST,27.0

In [5]:
df.sort_values("home_corner")

,tournament,home,home_goal,away_goal,away,home_corner,away_corner,home_attack,away_attack,home_shots,away_shots,time,date,ht_diff,at_diff,ht_result,at_result,total_corners
0,Premier League,Arsenal,0.0,0.0,Chelsea,0.0,0.0,NaN,NaN,NaN,NaN,20:00:00,2023-05-02,0.0,0.0,DRAW,DRAW,0.0
13895,England League 2,Bristol Rovers,1.0,2.0,Port Vale,0.0,4.0,72.0,103.0,5.0,14.0,19:45:00,2021-12-07,-1.0,1.0,LOST,WON,4.0
13759,England League 2,Carlisle,2.0,0.0,Rochdale,0.0,6.0,104.0,118.0,10.0,25.0,19:45:00,2022-03-01,2.0,-2.0,WON,LOST,6.0
13750,England League 2,Leyton Orient,2.0,2.0,Stevenage,0.0,4.0,128.0,122.0,9.0,9.0,15:00:00,2022-03-05,0.0,0.0,DRAW,DRAW,4.0
1210,Premier League,Crystal Palace,0.0,2.0,Southampton,0.0,8.0,113.0,149.0,6.0,15.0,19:30:00,2020-01-21,-2.0,2.0,LOST,WON,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13622,England League 2,Bristol Rovers,7.0,0.0,Scunthorpe,19.0,3.0,101.0,76.0,35.0,4.0,15:00:00,2022-05-07,7.0,-7.0,WON,LOST,22.0
14180,England League 2,Forest Green,3.0,2.0,Scunthorpe,19.0,1.0,87.0,74.0,17.0,7.0,12:30:00,2021-04-17,1.0,-1.0,WON,LOST,20.0
2484,Premier League,Man Utd,0.0,0.0,Burnley,19.0,1.0,115.0,81.0,36.0,7.0,15:00:00,2016-10-29,0.0,0.0,DRAW,DRAW,20.0
6666,England Championship,Newcastle,1.0,1.0,Leeds,19.0,0.0,124.0,100.0,20.0,4.0,19:45:00,2017-04-14,0.0,0.0,DRAW,DRAW,19.0
11766,England League 1,Sheff Utd,2.0,1.0,Shrewsbury,20.0,1.0,56.0,13.0,21.0,6.0,15:00:00,2016-11-19,1.0,-1.0,WON,LOST,21.0

In [7]:
df.sort_values("away_corner")

,tournament,home,home_goal,away_goal,away,home_corner,away_corner,home_attack,away_attack,home_shots,away_shots,time,date,ht_diff,at_diff,ht_result,at_result,total_corners
0,Premier League,Arsenal,0.0,0.0,Chelsea,0.0,0.0,NaN,NaN,NaN,NaN,20:00:00,2023-05-02,0.0,0.0,DRAW,DRAW,0.0
9978,England League 1,Accrington Stanley,2.0,1.0,AFC Wimbledon,3.0,0.0,89.0,106.0,12.0,7.0,15:00:00,2020-02-01,1.0,-1.0,WON,LOST,3.0
9990,England League 1,Gillingham,2.0,0.0,Shrewsbury,6.0,0.0,107.0,78.0,14.0,8.0,19:45:00,2020-01-29,2.0,-2.0,WON,LOST,6.0
18663,England National League,Notts County,3.0,1.0,Wrexham,2.0,0.0,116.0,99.0,10.0,7.0,15:00:00,2022-01-02,2.0,-2.0,WON,LOST,2.0
9995,England League 1,Doncaster,3.0,1.0,Southend,7.0,0.0,150.0,118.0,17.0,7.0,19:45:00,2020-01-28,2.0,-2.0,WON,LOST,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16731,England League 2,Crawley Town,1.0,1.0,Barnet,6.0,18.0,46.0,50.0,12.0,19.0,15:00:00,2016-08-20,0.0,0.0,DRAW,DRAW,24.0
12040,England League 1,Bury,1.0,0.0,Doncaster,9.0,18.0,NaN,NaN,NaN,NaN,15:00:00,2016-04-09,1.0,-1.0,WON,LOST,27.0
16986,England League 2,York,2.0,1.0,Notts County,2.0,18.0,NaN,NaN,NaN,NaN,15:00:00,2016-02-13,1.0,-1.0,WON,LOST,20.0
212,Premier League,Bournemouth,2.0,3.0,Tottenham,2.0,19.0,56.0,143.0,6.0,27.0,15:00:00,2022-10-29,-1.0,1.0,LOST,WON,21.0
12495,England League 1,Bury,3.0,4.0,Fleetwood Town,3.0,21.0,NaN,NaN,NaN,NaN,19:45:00,2015-08-18,-1.0,1.0,LOST,WON,24.0

In [8]:
df.sort_values("home_goal")

,tournament,home,home_goal,away_goal,away,home_corner,away_corner,home_attack,away_attack,home_shots,away_shots,time,date,ht_diff,at_diff,ht_result,at_result,total_corners
0,Premier League,Arsenal,0.0,0.0,Chelsea,0.0,0.0,NaN,NaN,NaN,NaN,20:00:00,2023-05-02,0.0,0.0,DRAW,DRAW,0.0
14726,England League 2,Northampton,0.0,1.0,Swindon,6.0,8.0,81.0,81.0,10.0,12.0,19:45:00,2020-02-11,-1.0,1.0,LOST,WON,14.0
14728,England League 2,Scunthorpe,0.0,2.0,Cambridge Utd,3.0,3.0,137.0,113.0,14.0,8.0,19:45:00,2020-02-11,-2.0,2.0,LOST,WON,6.0
5541,England Championship,Bolton,0.0,2.0,Aston Villa,2.0,16.0,105.0,106.0,6.0,21.0,15:00:00,2019-04-19,-2.0,2.0,LOST,WON,18.0
14737,England League 2,Newport County,0.0,1.0,Cambridge Utd,7.0,1.0,128.0,72.0,22.0,9.0,15:00:00,2020-02-08,-1.0,1.0,LOST,WON,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21515,England National League,Chester,8.0,2.0,Aldershot,6.0,5.0,NaN,NaN,NaN,NaN,19:45:00,2016-03-08,6.0,-6.0,WON,LOST,11.0
16215,England League 2,Luton,8.0,2.0,Yeovil,4.0,6.0,125.0,113.0,19.0,8.0,15:00:00,2017-08-05,6.0,-6.0,WON,LOST,10.0
1387,Premier League,Man City,8.0,0.0,Watford,5.0,4.0,128.0,64.0,29.0,5.0,15:00:00,2019-09-21,8.0,-8.0,WON,LOST,9.0
20962,England National League,Tranmere,9.0,0.0,Solihull Moors,5.0,3.0,98.0,90.0,23.0,7.0,15:00:00,2017-04-08,9.0,-9.0,WON,LOST,8.0
301,Premier League,Liverpool,9.0,0.0,Bournemouth,8.0,1.0,154.0,69.0,20.0,5.0,15:00:00,2022-08-27,9.0,-9.0,WON,LOST,9.0

In [9]:
df.sort_values("away_goal")

,tournament,home,home_goal,away_goal,away,home_corner,away_corner,home_attack,away_attack,home_shots,away_shots,time,date,ht_diff,at_diff,ht_result,at_result,total_corners
0,Premier League,Arsenal,0.0,0.0,Chelsea,0.0,0.0,NaN,NaN,NaN,NaN,20:00:00,2023-05-02,0.0,0.0,DRAW,DRAW,0.0
10696,England League 1,Bristol Rovers,0.0,0.0,Oxford Utd,3.0,4.0,55.0,42.0,16.0,11.0,15:00:00,2018-10-20,0.0,0.0,DRAW,DRAW,7.0
10697,England League 1,Charlton,2.0,0.0,Barnsley,5.0,7.0,97.0,94.0,14.0,18.0,15:00:00,2018-10-20,2.0,-2.0,WON,LOST,12.0
10699,England League 1,Luton,2.0,0.0,Walsall,12.0,5.0,63.0,51.0,14.0,5.0,15:00:00,2018-10-20,2.0,-2.0,WON,LOST,17.0
10702,England League 1,Portsmouth,1.0,0.0,Fleetwood Town,6.0,3.0,54.0,49.0,15.0,2.0,15:00:00,2018-10-20,1.0,-1.0,WON,LOST,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9034,England League 1,Gillingham,2.0,7.0,Oxford Utd,7.0,1.0,77.0,74.0,13.0,14.0,15:00:00,2022-01-29,-5.0,5.0,LOST,WON,8.0
11146,England League 1,Oxford Utd,0.0,7.0,Wigan,3.0,9.0,36.0,47.0,4.0,17.0,15:00:00,2017-12-23,-7.0,7.0,LOST,WON,12.0
8110,England Championship,Birmingham,0.0,8.0,Bournemouth,7.0,5.0,NaN,NaN,NaN,NaN,15:00:00,2014-10-25,-8.0,8.0,LOST,WON,12.0
21509,England National League,Cheltenham,4.0,9.0,Woking,9.0,4.0,NaN,NaN,NaN,NaN,15:00:00,2016-03-12,-5.0,5.0,LOST,WON,13.0
1349,Premier League,Southampton,0.0,9.0,Leicester,2.0,7.0,97.0,152.0,6.0,25.0,20:00:00,2019-10-25,-9.0,9.0,LOST,WON,9.0